doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        # Automatyczne mapowanie encji dla całej aplikacji
        auto_mapping: true
        # Automatyczne mapowanie encji dla kontrolerów (Symfony 6.4+ deprecation)
        controller_resolver:
            auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
                